README.md, frontend/src/App.tsx
=> Doc: add readme

README.md, frontend/src/App.tsx
=> Doc: update readme for frontend dev

.github/workflows/frontend-lint.yml, frontend/.prettierrc, frontend/LINT-README.md, frontend/package.json, frontend/pnpm-lock.yaml
=> Chore: GitHub action ci setup

frontend/.prettierrc, frontend/src/components/components.md, frontend/src/components/layout/layout.md, frontend/src/constants/constants.md, frontend/src/containers/containers.md, frontend/src/context/context.md, frontend/src/hooks/hooks.md, frontend/src/pages/pages.md, frontend/src/routes/routes.md, frontend/src/styles/styles.md, frontend/src/types/types.md, frontend/src/utils/utils.md
=> Doc: Add documentation for frontend project structure

.github/workflows/frontend-lint.yml, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/App.tsx, frontend/src/components/common/GlowEffect.tsx, frontend/src/components/common/GridPatternOverlay.tsx, frontend/src/components/landing/BrowserFrame.tsx, frontend/src/components/landing/FeatureBadge.tsx, frontend/src/components/landing/FeatureItem.tsx, frontend/src/components/landing/FeatureList.tsx, frontend/src/components/landing/HeroBackground.tsx, frontend/src/components/landing/HeroButton.tsx, frontend/src/components/landing/HeroButtons.tsx, frontend/src/components/landing/HeroContent.tsx, frontend/src/components/landing/HeroHeading.tsx, frontend/src/components/landing/HeroShowcase.tsx, frontend/src/components/landing/ProcessFlow.tsx, frontend/src/components/landing/ShowcaseBadge.tsx, frontend/src/constants/Landing/landingHero.ts, frontend/src/constants/index.ts, frontend/src/containers/Landing/HeroContainer.tsx, frontend/src/pages/LandingPage.tsx
=> Chore: update GitHub action ci setting

backend/InvoiceBackend/Controllers/InvoicesController.cs, backend/InvoiceBackend/Program.cs, frontend/netlify.toml, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/App.tsx, frontend/src/components/InvoiceList.tsx, frontend/src/components/example/InvoiceList.tsx, frontend/src/constants/config.ts, frontend/src/constants/index.ts, frontend/src/hooks/useInvoices.ts, frontend/src/lib/axios.ts, frontend/src/pages/ApiTestPage.tsx, frontend/src/routes/index.tsx, frontend/src/types/invoice.ts
=> Chore: react query axio setup

.gitignore, frontend/.env.example, frontend/.gitignore, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/auth/AuthButtonGroup.tsx, frontend/src/components/auth/ProtectedRoute.tsx, frontend/src/components/auth/SignInButton.tsx, frontend/src/components/auth/SignUpButton.tsx, frontend/src/components/layout/LandingLayout.tsx, frontend/src/lib/api.ts, frontend/src/lib/axios.ts, frontend/src/main.tsx, frontend/src/routes/index.tsx
- Added ClerkProvider to main application for authentication.
- Created AuthButtonGroup component for sign-in and sign-up buttons.
- Implemented ProtectedRoute component to guard routes based on authentication status.
- Updated .env.example for Clerk publishable key configuration.
- Configured Axios instances to include Clerk authentication tokens in requests.
- Added new components for sign-in and sign-up buttons.
- Updated LandingLayout to include authentication buttons.
=> feat: Integrate Clerk authentication into frontend

frontend/src/containers/NotFoundContainer.tsx, frontend/src/routes/index.tsx
- Removed the previous 404 page route from the public routes section.
- Added a new 404 page route without layout for better handling of unmatched paths.
=> Refactor: Update 404 page routing in index.tsx

frontend/src/components/landing/HeroButtons.tsx, frontend/src/routes/index.tsx
=> Feat: add route protection

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/common/DashboardHeader.tsx, frontend/src/components/common/LandingHeader.tsx, frontend/src/components/common/LogoTextGroup.tsx, frontend/src/components/layout/DashboardLayout.tsx, frontend/src/components/ui/collapsible.tsx, frontend/src/components/ui/navigation-menu.tsx, frontend/src/components/ui/popover.tsx, frontend/src/components/ui/sheet.tsx
=> Feat  dashboard header

frontend/src/components/auth/ProtectedRoute.tsx, frontend/src/containers/LoadingContainer.tsx, frontend/src/pages/LoadingPage.tsx, frontend/src/routes/index.tsx
- Added a new LoadingContainer component for a visually appealing loading state with animations and messages.
- Created a LoadingPage component that utilizes LoadingContainer for consistent loading experience.
- Updated ProtectedRoute to display LoadingPage while authentication is in progress.
- Introduced a new route for loading state at "/loading" in the routing configuration.
=> Feat: Implement loading page and container

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/common/FormField.tsx, frontend/src/components/ui/alert-dialog.tsx, frontend/src/containers/Customers/CustomerTableContainer.tsx, frontend/src/containers/Customers/DeleteCustomerDialog.tsx, frontend/src/hooks/useDeleteCustomer.ts, frontend/src/pages/CustomersPage.tsx
=> Feat: add cuntom delete

frontend/src/components/common/Footer.tsx, frontend/src/components/common/LandingHeader.tsx, frontend/src/containers/Landing/FeatureSectionContainer.tsx, frontend/src/containers/Landing/ProcessContainer.tsx, frontend/src/index.css
- Added smooth scrolling behavior to the HTML element.
- Updated Footer component to use anchor tags for internal links.
- Adjusted LandingHeader component's navigation for better spacing and updated FAQ link.
- Added IDs to FeatureSectionContainer and ProcessContainer for improved navigation targeting.
=> feat: Enhance landing page navigation and styling

frontend/src/containers/Customers/CreateCustomerContainer.tsx, frontend/src/containers/Customers/EditCustomerContainer.tsx
=> feat: Update country code placeholder from "+1" to "+61"

frontend/src/components/landing/BenefitsPage/BenefitsBackground.tsx, frontend/src/components/landing/ProcessBackground.tsx
=> feat: update landing background

frontend/src/containers/Invoices/InvoiceTableContainer.tsx, frontend/src/types/invoice.ts
=> Fix：Invoice table search sort

frontend/src/containers/Invoices/CreateInvoiceContainer.tsx, frontend/src/containers/Invoices/InvoicePdfUploadContainer.tsx, frontend/src/hooks/invoice/usePreprocessInvoiceData.ts, frontend/src/hooks/invoice/useProcessInvoicePdf.ts, frontend/src/utils/formatters.ts
=> Feat: upload pdf update

frontend/src/components/landing/FAQ_Page/FAQBackground.tsx, frontend/src/constants/Documentation/BusinessProcess.ts, frontend/src/constants/Documentation/Integration.ts, frontend/src/constants/Documentation/SideBar.tsx, frontend/src/containers/Documentation/BusinessProcessContainer.tsx, frontend/src/containers/Documentation/InvoiceCreationContainer.tsx, frontend/src/containers/Documentation/OverviewContainer.tsx, frontend/src/containers/Documentation/ReckonIntegrationContainer.tsx, frontend/src/containers/Documentation/SMEGuidelinesContainer.tsx, frontend/src/containers/Documentation/SendingContainer.tsx, frontend/src/containers/Documentation/SideBarContainer.tsx, frontend/src/containers/Documentation/UBLConversionContainer.tsx, frontend/src/containers/Documentation/ValidationContainer.tsx, frontend/src/containers/Landing/BenefitsContainer.tsx, frontend/src/pages/DocumentationPage.tsx, frontend/src/routes/index.tsx
This part still needs some work. I’ll pick it up after the presentation.
=> Feat documentation page

frontend/src/components/common/DashboardHeader.tsx
/management/customers -> /customers
/management/products -> /products
/management/invoices -> /invoices
=> fix: Fix mobile navigation links in Management menu

backend/InvoiceBackend/Controllers/InvoicesController.cs, frontend/src/components/invoice/InvoiceDetails.tsx, frontend/src/components/invoice/InvoiceInformation.tsx, frontend/src/components/invoice/InvoiceItems.tsx, frontend/src/components/invoice/InvoiceTotal.tsx, frontend/src/containers/Invoices/EditInvoiceContainer.tsx
add a refresh to fix invoice lineitem bug(only show the first line)
split the editinvoice file
=> Fix  edit invoice

frontend/src/components/invoice/ValidationResultModal.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/containers/Invoices/InvoiceTableContainer.tsx, frontend/src/containers/Invoices/ViewInvoicContainer.tsx, frontend/src/hooks/invoice/useValidateInvoicePeppol.ts
- Implemented ValidationResultModal component to display invoice validation results.
- Integrated validation logic in ViewInvoiceContainer using useValidateInvoicePeppol hook.
- Added buttons for validating invoices and handling validation results.
- Created useValidateInvoicePeppol hook for AI-based invoice validation against PEPPOL requirements.
- Introduced dialog components for consistent modal UI.
=> feat: add a simple validation functionality 

frontend/src/containers/Customers/CreateCustomerContainer.tsx, frontend/src/containers/Products/CreateProductContainer.tsx
- Enhanced error handling logic for customer and product creation forms.
- Error toasts now display clear backend validation messages (from `error.response.data.message`) instead of generic `[object Object]`.
=> fix: improve error toast for customer and product creation with backend message

frontend/src/pages/CreateCustomerPage.tsx, frontend/src/pages/CreateProductPage.tsx, frontend/src/pages/CustomersPage.tsx, frontend/src/pages/DashboardPage.tsx, frontend/src/pages/DocumentationPage.tsx, frontend/src/pages/EditCustomerPage.tsx, frontend/src/pages/EditProductPage.tsx, frontend/src/pages/InvoicePdfUploadPage.tsx, frontend/src/pages/LandingPage.tsx, frontend/src/pages/LoadingPage.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/NotFoundPage.tsx, frontend/src/pages/ProductsPage.tsx, frontend/src/pages/ReckonCallbackPage.tsx, frontend/src/pages/RegistrationPage.tsx, frontend/src/pages/SelectIntegrationPage.tsx, frontend/src/pages/invoices/CreateInvoicePage.tsx, frontend/src/pages/invoices/EditInvoicePage.tsx, frontend/src/pages/invoices/InvoicesPage.tsx, frontend/src/pages/invoices/ViewInvoicePage.tsx
This PR adds structured in-code documentation for all page-level React components in the project.
=> add in-code-documentation: pages

frontend/src/hooks/account/useAccounts.ts, frontend/src/hooks/book/useBookCustomer.ts, frontend/src/hooks/customer/useCreateCustomer.ts, frontend/src/hooks/customer/useCustomer.ts, frontend/src/hooks/customer/useCustomers.ts, frontend/src/hooks/customer/useDeleteCustomer.ts, frontend/src/hooks/customer/useEditCustomer.ts, frontend/src/hooks/invoice/useCreateInvoice.ts, frontend/src/hooks/invoice/useDeleteInvoice.ts, frontend/src/hooks/invoice/useDownloadInvoice.ts, frontend/src/hooks/invoice/useEditInvoice.ts, frontend/src/hooks/invoice/useInvoice.ts, frontend/src/hooks/invoice/useInvoices.ts, frontend/src/hooks/invoice/usePreprocessInvoiceData.ts, frontend/src/hooks/invoice/useProcessInvoicePdf.ts, frontend/src/hooks/invoice/useSendInvoice.ts, frontend/src/hooks/invoice/useValidateInvoicePeppol.ts, frontend/src/hooks/payment/useDueDate.ts, frontend/src/hooks/payment/usePaymentTerms.ts, frontend/src/hooks/product/useCreateProduct.ts, frontend/src/hooks/product/useDeleteProduct.ts, frontend/src/hooks/product/useEditProduct.ts, frontend/src/hooks/product/useProduct.ts, frontend/src/hooks/product/useProducts.ts, frontend/src/hooks/reckon/useConnectReckon.ts, frontend/src/hooks/reckon/useReckonCallback.ts, frontend/src/hooks/useTestInvoices.ts
This PR adds structured in-code documentation for all custom React hooks in the project.
=> docs: add in-code documentation to hooks

frontend/src/containers/Products/CreateProductContainer.tsx, frontend/src/containers/Products/EditProductContainer.tsx
=> remove ledger account selection

frontend/src/hooks/invoice/useValidateInvoicePeppol.ts
=> fix: update invoice validation  prompt 

frontend/src/containers/Customers/DeleteCustomerDialog.tsx, frontend/src/containers/Invoices/DeleteInvoiceDialog.tsx, frontend/src/containers/Products/DeleteProductDialog.tsx
This PR improves the error handling logic for delete actions across Customer, Product, and Invoice entities. It ensures consistent error messages and better feedback from backend responses.
=> fix: unify delete error messages for customer, product, and invoice

frontend/src/__tests__/Footer.test.tsx, frontend/src/__tests__/FormField.test.tsx, frontend/src/__tests__/GlowEffect.test.tsx, frontend/src/__tests__/GlowHoverEffect.test.tsx, frontend/src/__tests__/GradientAccentLine.test.tsx, frontend/src/__tests__/GridPatternOverlay.test.tsx, frontend/src/__tests__/LandingHeader.test.tsx, frontend/src/__tests__/Logo.test.tsx, frontend/src/__tests__/LogoTextGroup.test.tsx, frontend/src/__tests__/MinimalHeader.test.tsx
Added unit tests for the following components:
- Footer
- FormField
- GlowEffect
- GlowHoverEffect
- GradientAccentLine
- GridPatternOverlay
- LandingHeader
- Logo
- LogoTextGroup
- MinimalHeader
=> test: add unit tests for 10 common components

frontend/src/App.tsx, frontend/src/hooks/customer/useCreateCustomer.ts, frontend/src/hooks/customer/useDeleteCustomer.ts, frontend/src/hooks/customer/useEditCustomer.ts, frontend/src/hooks/invoice/useCreateInvoice.ts, frontend/src/hooks/invoice/useDeleteInvoice.ts, frontend/src/hooks/invoice/useEditInvoice.ts, frontend/src/hooks/invoice/useSendInvoice.ts, frontend/src/hooks/product/useCreateProduct.ts, frontend/src/hooks/product/useDeleteProduct.ts, frontend/src/hooks/product/useEditProduct.ts
=> Fix: fetch data delay bug

frontend/src/hooks/invoice/useProcessInvoicePdf.ts
=> fix: update PDF crash bug

frontend/src/components/common/Footer.tsx, frontend/src/components/landing/FAQ_Page/FAQHelpSection.tsx, frontend/src/components/landing/KeyFeatureHighlight.tsx, frontend/src/constants/Landing/landingFAQ.tsx, frontend/src/constants/Landing/landingFeature.ts, frontend/src/constants/Landing/landingHero.ts, frontend/src/constants/Landing/landingProcess.ts, frontend/src/constants/Landing/landingbenefits.tsx, frontend/src/pages/DocumentationPage.tsx
=> Feat: update landing page content
